Repository OntimizeWeb/ontimize-web-ngx-gallery, pull requests merged in 2022-07, with the labels that each got.

#45 solved bugs
  CHANGELOG.md
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-action/o-gallery-action.component.html
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-arrows/o-gallery-arrows.component.html
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-arrows/o-gallery-arrows.component.scss
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-preview/o-gallery-preview.component.html
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-preview/o-gallery-preview.component.ts
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery/o-gallery.component.ts
  projects/ontimize-web-ngx-gallery/src/lib/services/gallery-helper.service.ts
Labels: bug

#44 Fix image type detection when url contains query parameters
  package.json
  projects/ontimize-web-ngx-gallery/package.json
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-image/o-gallery-image.component.html
  projects/ontimize-web-ngx-gallery/src/lib/services/gallery-helper.service.ts
Labels: bug

#47 Release and CI workflows
  .github/workflows/build-ci.yml
  .github/workflows/build-release.yml
Labels: enhancement

#49 Release 8.0.3
  .github/workflows/build-ci.yml
  .github/workflows/build-release.yml
  CHANGELOG.md
  package.json
  projects/ontimize-web-ngx-gallery/package.json
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-image/o-gallery-image.component.html
  projects/ontimize-web-ngx-gallery/src/lib/services/gallery-helper.service.ts
Labels: release-type

#52 Fix npm publish
  .github/workflows/build-release.yml
Labels: bug

#56 modified gallery component
  CHANGELOG.md
  projects/ontimize-web-ngx-gallery/package.json
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-preview/o-gallery-preview.component.scss
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery-preview/o-gallery-preview.component.ts
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery/o-gallery.component.html
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery/o-gallery.component.scss
  projects/ontimize-web-ngx-gallery/src/lib/components/gallery/o-gallery.component.ts
  projects/ontimize-web-ngx-gallery/src/lib/ontimize-web-ngx-gallery.module.ts
Labels: bug
